server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-authuser-v2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#    addresses: amqps://bohdqncv:V21FA7kO8cgRFUVzGzjanVQv2nKWAzMN@gull.rmq.cloudamqp.com/bohdqncv
# site: https://gull.rmq.cloudamqp.com/#/connections


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course/'
  broker:
    exchange:
      userEvent: ead.userevent

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

resilience4j:
  retry:
    instances:
      retryInstance:
        max-attempts: 3
        wait-duration: 5s


